import { useState, useRef, useEffect } from 'react';
import { getAllMockProjects } from '../data/projectData';
import { getAllProjects } from '../utils/storage';

/* ── Helpers ────────────────────────────────────────────────────────── */
function initials(addr) {
  return (addr || 'XX').split(' ').slice(0, 2).map(w => w[0]).join('').toUpperCase();
}
const AVATAR_COLORS = ['#2563eb','#7c3aed','#0891b2','#059669','#d97706','#dc2626','#0f766e'];
function avatarColor(str) {
  let h = 0; for (const c of (str||'')) h = (h * 31 + c.charCodeAt(0)) % AVATAR_COLORS.length;
  return AVATAR_COLORS[h];
}
function fmt(n) { return Math.round(n).toLocaleString(); }

const EDGE_LABELS = {
  eave:          { label: 'Eaves',         color: '#16a34a' },
  ridge:         { label: 'Ridges',        color: '#14b8a6' },
  valley:        { label: 'Valleys',       color: '#ef4444' },
  hip:           { label: 'Hips',          color: '#a855f7' },
  rake:          { label: 'Rakes',         color: '#f59e0b' },
  wall_flashing: { label: 'Wall Flashing', color: '#3b82f6' },
  step_flashing: { label: 'Step Flashing', color: '#ec4899' },
};

const MSGS_KEY = 'insurance-comms-messages';
function loadMsgs() {
  try { const d = localStorage.getItem(MSGS_KEY); return d ? JSON.parse(d) : {}; } catch { return {}; }
}
function saveMsgs(data) { localStorage.setItem(MSGS_KEY, JSON.stringify(data)); }

/* ── Build the measurement text block ──────────────────────────────── */
function buildMeasurementText(project) {
  const m = project.measurements;
  if (!m) return `Address: ${project.address}\nCompleted: ${project.completedAt}\n\nNo measurement data available.`;

  const edges = Object.entries(m.edgeSummary || {}).filter(([,v]) => v > 0)
    .map(([k, v]) => `  ${EDGE_LABELS[k]?.label || k}: ${fmt(v)} ft`).join('\n');

  const facets = (m.facets || [])
    .map(f => `  ${f.id}: ${fmt(f.area)} sq ft @ ${f.pitch}`).join('\n');

  return `ROOF MEASUREMENT REPORT
========================
Address:        ${project.address}
Completed:      ${project.completedAt}
Type:           ${project.type || 'DIY'}
Assignee:       ${project.assignee || 'Ahjin Roofing'}

SUMMARY
-------
Footprint Area: ${fmt(m.totalFootprintArea)} sq ft
Total Roof Area:${fmt(m.totalRoofArea)} sq ft
Pitch:          ${m.pitch}
Squares:        ${(m.totalRoofArea / 100).toFixed(1)} squares

ROOF PLANES
-----------
${facets || '  No plane data'}

EDGE MEASUREMENTS
-----------------
${edges || '  No edge data'}

Generated by Ahjin Roofing System`;
}

/* ════════════════════════════════════════════════════════════════════ */
export default function InsuranceCommunication() {
  // Load completed projects
  const allProjects = (() => {
    const mock = getAllMockProjects();
    const saved = getAllProjects();
    const merged = [...mock];
    saved.forEach(s => {
      const idx = merged.findIndex(p => p.id === s.id);
      if (idx >= 0) merged[idx] = { ...merged[idx], ...s };
      else merged.push(s);
    });
    return merged.filter(p => p.completedAt && p.completedAt !== '-');
  })();

  const [search,      setSearch]      = useState('');
  const [activeId,    setActiveId]    = useState(allProjects[0]?.id || null);
  const [channel,     setChannel]     = useState('email');
  const [recipient,   setRecipient]   = useState('');
  const [msgText,     setMsgText]     = useState('');
  const [pendingFiles,setPendingFiles]= useState([]);
  const [threads,     setThreads]     = useState(() => loadMsgs());
  const [toast,       setToast]       = useState(null);

  const fileRef    = useRef(null);
  const threadEnd  = useRef(null);
  const textRef    = useRef(null);

  const activeProject = allProjects.find(p => p.id === activeId);
  const thread = threads[activeId] || [];

  const filtered = allProjects.filter(p =>
    !search || (p.address||'').toLowerCase().includes(search.toLowerCase())
  );

  useEffect(() => {
    threadEnd.current?.scrollIntoView({ behavior: 'smooth' });
  }, [thread.length, activeId]);

  const showToast = (msg, type = 'success') => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3500);
  };

  const handleFileChange = (e) => {
    const files = Array.from(e.target.files).map(f => ({
      name: f.name,
      size: f.size > 1048576 ? `${(f.size/1048576).toFixed(1)} MB` : `${Math.round(f.size/1024)} KB`,
      type: f.name.split('.').pop().toLowerCase(),
    }));
    setPendingFiles(prev => [...prev, ...files]);
    e.target.value = '';
  };

  const includeDetails = () => {
    const block = buildMeasurementText(activeProject);
    setMsgText(prev => prev ? prev + '\n\n' + block : block);
    textRef.current?.focus();
  };

  const send = () => {
    if (!recipient.trim()) { showToast('Please enter a recipient.', 'error'); return; }
    if (!msgText.trim() && pendingFiles.length === 0) { showToast('Message is empty.', 'error'); return; }

    const newMsg = {
      id: Date.now().toString(),
      channel,
      dir: 'out',
      to: recipient.trim(),
      body: msgText.trim(),
      files: pendingFiles,
      time: new Date().toISOString(),
    };
    const updated = { ...threads, [activeId]: [...thread, newMsg] };
    setThreads(updated);
    saveMsgs(updated);
    setMsgText('');
    setPendingFiles([]);
    showToast(`Sent via ${channel === 'email' ? 'Email' : 'SMS'} to ${recipient}`);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); }
  };

  const formatTime = (iso) => {
    const d = new Date(iso);
    return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  };

  /* ── Render ── */
  return (
    <div className="ic-page">

      {/* ══ LEFT PANEL ══ */}
      <div className="ic-sidebar">
        <div className="ic-sidebar-header">
          <h1 className="ic-sidebar-title">Insurance Comms</h1>
          <p className="ic-sidebar-sub">Completed measurements</p>
          <div className="ic-search-wrap">
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2">
              <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
            </svg>
            <input
              className="ic-search"
              placeholder="Search address..."
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
          </div>
        </div>

        <div className="ic-project-list">
          {filtered.length === 0 && <div className="ic-empty-list">No completed measurements</div>}
          {filtered.map(p => {
            const hasSent = (threads[p.id] || []).length > 0;
            return (
              <div
                key={p.id}
                className={`ic-project-item ${activeId === p.id ? 'active' : ''}`}
                onClick={() => setActiveId(p.id)}
              >
                <div className="ic-avatar" style={{ background: avatarColor(p.address) }}>
                  {initials(p.address)}
                </div>
                <div className="ic-project-info">
                  <div className="ic-project-addr">{p.address}</div>
                  <div className="ic-project-meta">
                    <span className="ic-completed-dot" />
                    {p.completedAt}
                  </div>
                </div>
                <div className="ic-project-right">
                  {p.measurements && (
                    <span className="ic-sqft-badge">{fmt(p.measurements.totalRoofArea)} sqft</span>
                  )}
                  {hasSent && (
                    <span className="ic-sent-badge" title="Messages sent">
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <polyline points="20 6 9 17 4 12"/>
                      </svg>
                    </span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* ══ RIGHT PANEL ══ */}
      <div className="ic-main">
        {!activeProject ? (
          <div className="ic-no-select">
            <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="#cbd5e1" strokeWidth="1.2">
              <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
              <polyline points="22,6 12,13 2,6"/>
            </svg>
            <p>Select a completed measurement to send details</p>
          </div>
        ) : (
          <>
            {/* Header */}
            <div className="ic-main-header">
              <div>
                <div className="ic-main-addr">{activeProject.address}</div>
                <div className="ic-main-sub">
                  Completed: <strong>{activeProject.completedAt}</strong>
                  &nbsp;·&nbsp; {activeProject.type}
                  &nbsp;·&nbsp; {activeProject.assignee || 'Ahjin Roofing'}
                </div>
              </div>
              {/* Channel tabs */}
              <div className="ic-ch-tabs">
                {['email','sms'].map(ch => (
                  <button
                    key={ch}
                    className={`ic-ch-tab ${ch} ${channel === ch ? 'active' : ''}`}
                    onClick={() => setChannel(ch)}
                  >
                    {ch === 'email' ? (
                      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
                        <polyline points="22,6 12,13 2,6"/>
                      </svg>
                    ) : (
                      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>
                      </svg>
                    )}
                    {ch === 'email' ? 'Email' : 'SMS'}
                  </button>
                ))}
              </div>
            </div>

            {/* Measurement summary strip */}
            {activeProject.measurements && (
              <div className="ic-summary-strip">
                <div className="ic-summary-item">
                  <span className="ic-summary-label">Footprint</span>
                  <span className="ic-summary-val">{fmt(activeProject.measurements.totalFootprintArea)} sqft</span>
                </div>
                <div className="ic-summary-divider"/>
                <div className="ic-summary-item">
                  <span className="ic-summary-label">Roof Area</span>
                  <span className="ic-summary-val blue">{fmt(activeProject.measurements.totalRoofArea)} sqft</span>
                </div>
                <div className="ic-summary-divider"/>
                <div className="ic-summary-item">
                  <span className="ic-summary-label">Pitch</span>
                  <span className="ic-summary-val">{activeProject.measurements.pitch}</span>
                </div>
                <div className="ic-summary-divider"/>
                <div className="ic-summary-item">
                  <span className="ic-summary-label">Squares</span>
                  <span className="ic-summary-val">{(activeProject.measurements.totalRoofArea/100).toFixed(1)}</span>
                </div>
                <div className="ic-summary-divider"/>
                <div className="ic-summary-item">
                  <span className="ic-summary-label">Edges</span>
                  <span className="ic-summary-val" style={{fontSize:11}}>
                    {Object.entries(activeProject.measurements.edgeSummary||{})
                      .filter(([,v])=>v>0)
                      .map(([k,v])=>`${EDGE_LABELS[k]?.label||k}: ${v}ft`)
                      .join(' · ')}
                  </span>
                </div>
              </div>
            )}

            {/* Thread */}
            <div className="ic-thread">
              {thread.length === 0 && (
                <div className="ic-thread-empty">
                  No messages sent yet for this measurement.
                </div>
              )}
              {thread.map(m => (
                <div key={m.id} className="ic-msg">
                  <div className="ic-msg-bubble">
                    <div className="ic-msg-channel">
                      {m.channel === 'email' ? (
                        <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
                          <polyline points="22,6 12,13 2,6"/>
                        </svg>
                      ) : (
                        <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>
                        </svg>
                      )}
                      To: {m.to}
                    </div>
                    {m.body && <pre className="ic-msg-body">{m.body}</pre>}
                    {m.files && m.files.length > 0 && (
                      <div className="ic-msg-files">
                        {m.files.map((f,i) => (
                          <div key={i} className="ic-file-chip">
                            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48"/>
                            </svg>
                            {f.name} <span>({f.size})</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                  <div className="ic-msg-time">{formatTime(m.time)}</div>
                </div>
              ))}
              <div ref={threadEnd}/>
            </div>

            {/* Compose */}
            <div className="ic-compose">
              {/* Recipient */}
              <div className="ic-recipient-row">
                <span className="ic-to-label">To:</span>
                <input
                  className="ic-recipient-input"
                  placeholder={channel === 'email' ? 'adjuster@insurancecompany.com' : '+1 (555) 000-0000'}
                  value={recipient}
                  onChange={e => setRecipient(e.target.value)}
                />
              </div>

              {/* Attach preview */}
              {pendingFiles.length > 0 && (
                <div className="ic-attach-preview">
                  {pendingFiles.map((f,i) => (
                    <div key={i} className="ic-attach-chip">
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <path d="M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48"/>
                      </svg>
                      {f.name}
                      <button onClick={()=>setPendingFiles(p=>p.filter((_,idx)=>idx!==i))}>×</button>
                    </div>
                  ))}
                </div>
              )}

              {/* Compose box */}
              <div className="ic-compose-box">
                <textarea
                  ref={textRef}
                  className="ic-compose-input"
                  placeholder={`Type your message to the insurance company... (Enter to send)`}
                  value={msgText}
                  onChange={e => setMsgText(e.target.value)}
                  onKeyDown={handleKeyDown}
                  rows={3}
                />
              </div>

              {/* Action bar */}
              <div className="ic-action-bar">
                <div className="ic-action-left">
                  <input type="file" ref={fileRef} style={{display:'none'}} multiple onChange={handleFileChange}/>
                  <button className="ic-action-btn" onClick={()=>fileRef.current?.click()} title="Attach file">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48"/>
                    </svg>
                    Attach File
                  </button>
                  <button className="ic-action-btn accent" onClick={includeDetails} title="Include measurement data in message">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/>
                    </svg>
                    Include Measurement Details
                  </button>
                </div>
                <button
                  className="ic-send-btn"
                  onClick={send}
                  disabled={!recipient.trim() && !msgText.trim() && pendingFiles.length === 0}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <line x1="22" y1="2" x2="11" y2="13"/>
                    <polygon points="22 2 15 22 11 13 2 9 22 2"/>
                  </svg>
                  Send via {channel === 'email' ? 'Email' : 'SMS'}
                </button>
              </div>
            </div>
          </>
        )}
      </div>

      {/* Toast */}
      {toast && (
        <div className={`ic-toast ${toast.type}`}>
          {toast.type === 'success' ? (
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <polyline points="20 6 9 17 4 12"/>
            </svg>
          ) : (
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
            </svg>
          )}
          {toast.msg}
        </div>
      )}
    </div>
  );
}
